# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='media/photos'),
        ),
    ]
